// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * EC2NodeClass is the Schema for the EC2NodeClass API
 */
export class EC2NodeClass extends pulumi.CustomResource {
    /**
     * Get an existing EC2NodeClass resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EC2NodeClass {
        return new EC2NodeClass(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:karpenter.k8s.aws/v1:EC2NodeClass';

    /**
     * Returns true if the given object is an instance of EC2NodeClass.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EC2NodeClass {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EC2NodeClass.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"karpenter.k8s.aws/v1" | undefined>;
    public readonly kind!: pulumi.Output<"EC2NodeClass" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * EC2NodeClassSpec is the top level specification for the AWS Karpenter Provider.
     * This will contain configuration necessary to launch instances in AWS.
     */
    public readonly spec!: pulumi.Output<outputs.karpenter.v1.EC2NodeClassSpec | undefined>;
    /**
     * EC2NodeClassStatus contains the resolved state of the EC2NodeClass
     */
    public readonly status!: pulumi.Output<outputs.karpenter.v1.EC2NodeClassStatus | undefined>;

    /**
     * Create a EC2NodeClass resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: EC2NodeClassArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "karpenter.k8s.aws/v1";
            resourceInputs["kind"] = "EC2NodeClass";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.karpenter.v1.ec2nodeClassSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EC2NodeClass.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EC2NodeClass resource.
 */
export interface EC2NodeClassArgs {
    apiVersion?: pulumi.Input<"karpenter.k8s.aws/v1">;
    kind?: pulumi.Input<"EC2NodeClass">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * EC2NodeClassSpec is the top level specification for the AWS Karpenter Provider.
     * This will contain configuration necessary to launch instances in AWS.
     */
    spec?: pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecArgs>;
    /**
     * EC2NodeClassStatus contains the resolved state of the EC2NodeClass
     */
    status?: pulumi.Input<inputs.karpenter.v1.EC2NodeClassStatusArgs>;
}
