// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { EC2NodeClassArgs } from "./ec2nodeClass";
export type EC2NodeClass = import("./ec2nodeClass").EC2NodeClass;
export const EC2NodeClass: typeof import("./ec2nodeClass").EC2NodeClass = null as any;
utilities.lazyLoad(exports, ["EC2NodeClass"], () => require("./ec2nodeClass"));

export { NodeClaimArgs } from "./nodeClaim";
export type NodeClaim = import("./nodeClaim").NodeClaim;
export const NodeClaim: typeof import("./nodeClaim").NodeClaim = null as any;
utilities.lazyLoad(exports, ["NodeClaim"], () => require("./nodeClaim"));

export { NodePoolArgs } from "./nodePool";
export type NodePool = import("./nodePool").NodePool;
export const NodePool: typeof import("./nodePool").NodePool = null as any;
utilities.lazyLoad(exports, ["NodePool"], () => require("./nodePool"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:karpenter.k8s.aws/v1:EC2NodeClass":
                return new EC2NodeClass(name, <any>undefined, { urn })
            case "kubernetes:karpenter.sh/v1:NodeClaim":
                return new NodeClaim(name, <any>undefined, { urn })
            case "kubernetes:karpenter.sh/v1:NodePool":
                return new NodePool(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("karpenter-pulumi", "karpenter.k8s.aws/v1", _module)
pulumi.runtime.registerResourceModule("karpenter-pulumi", "karpenter.sh/v1", _module)
