// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * NodeClaim is the Schema for the NodeClaims API
 */
export class NodeClaim extends pulumi.CustomResource {
    /**
     * Get an existing NodeClaim resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NodeClaim {
        return new NodeClaim(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:karpenter.sh/v1:NodeClaim';

    /**
     * Returns true if the given object is an instance of NodeClaim.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NodeClaim {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NodeClaim.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"karpenter.sh/v1" | undefined>;
    public readonly kind!: pulumi.Output<"NodeClaim" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * NodeClaimSpec describes the desired state of the NodeClaim
     */
    public readonly spec!: pulumi.Output<outputs.karpenter.v1.NodeClaimSpec>;
    /**
     * NodeClaimStatus defines the observed state of NodeClaim
     */
    public readonly status!: pulumi.Output<outputs.karpenter.v1.NodeClaimStatus | undefined>;

    /**
     * Create a NodeClaim resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NodeClaimArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "karpenter.sh/v1";
            resourceInputs["kind"] = "NodeClaim";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.karpenter.v1.nodeClaimSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NodeClaim.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NodeClaim resource.
 */
export interface NodeClaimArgs {
    apiVersion?: pulumi.Input<"karpenter.sh/v1">;
    kind?: pulumi.Input<"NodeClaim">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * NodeClaimSpec describes the desired state of the NodeClaim
     */
    spec?: pulumi.Input<inputs.karpenter.v1.NodeClaimSpecArgs>;
    /**
     * NodeClaimStatus defines the observed state of NodeClaim
     */
    status?: pulumi.Input<inputs.karpenter.v1.NodeClaimStatusArgs>;
}
