// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * NodePool is the Schema for the NodePools API
 */
export class NodePool extends pulumi.CustomResource {
    /**
     * Get an existing NodePool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NodePool {
        return new NodePool(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:karpenter.sh/v1:NodePool';

    /**
     * Returns true if the given object is an instance of NodePool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NodePool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NodePool.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"karpenter.sh/v1" | undefined>;
    public readonly kind!: pulumi.Output<"NodePool" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * NodePoolSpec is the top level nodepool specification. Nodepools
     * launch nodes in response to pods that are unschedulable. A single nodepool
     * is capable of managing a diverse set of nodes. Node properties are determined
     * from a combination of nodepool and pod scheduling constraints.
     */
    public readonly spec!: pulumi.Output<outputs.karpenter.v1.NodePoolSpec>;
    /**
     * NodePoolStatus defines the observed state of NodePool
     */
    public readonly status!: pulumi.Output<outputs.karpenter.v1.NodePoolStatus | undefined>;

    /**
     * Create a NodePool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NodePoolArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "karpenter.sh/v1";
            resourceInputs["kind"] = "NodePool";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.karpenter.v1.nodePoolSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? (args.status ? pulumi.output(args.status).apply(inputs.karpenter.v1.nodePoolStatusArgsProvideDefaults) : undefined) : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NodePool.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NodePool resource.
 */
export interface NodePoolArgs {
    apiVersion?: pulumi.Input<"karpenter.sh/v1">;
    kind?: pulumi.Input<"NodePool">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * NodePoolSpec is the top level nodepool specification. Nodepools
     * launch nodes in response to pods that are unschedulable. A single nodepool
     * is capable of managing a diverse set of nodes. Node properties are determined
     * from a combination of nodepool and pod scheduling constraints.
     */
    spec?: pulumi.Input<inputs.karpenter.v1.NodePoolSpecArgs>;
    /**
     * NodePoolStatus defines the observed state of NodePool
     */
    status?: pulumi.Input<inputs.karpenter.v1.NodePoolStatusArgs>;
}
