// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

import {ObjectMeta} from "../meta/v1";

export namespace karpenter {
    export namespace v1 {
        /**
         * EC2NodeClassSpec is the top level specification for the AWS Karpenter Provider.
         * This will contain configuration necessary to launch instances in AWS.
         */
        export interface EC2NodeClassSpecArgs {
            /**
             * AMIFamily dictates the UserData format and default BlockDeviceMappings used when generating launch templates.
             * This field is optional when using an alias amiSelectorTerm, and the value will be inferred from the alias'
             * family. When an alias is specified, this field may only be set to its corresponding family or 'Custom'. If no
             * alias is specified, this field is required.
             * NOTE: We ignore the AMIFamily for hashing here because we hash the AMIFamily dynamically by using the alias using
             * the AMIFamily() helper function
             */
            amiFamily?: pulumi.Input<string>;
            /**
             * AMISelectorTerms is a list of or ami selector terms. The terms are ORed.
             */
            amiSelectorTerms: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecAmiSelectorTermsArgs>[]>;
            /**
             * AssociatePublicIPAddress controls if public IP addresses are assigned to instances that are launched with the nodeclass.
             */
            associatePublicIPAddress?: pulumi.Input<boolean>;
            /**
             * BlockDeviceMappings to be applied to provisioned nodes.
             */
            blockDeviceMappings?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecBlockDeviceMappingsArgs>[]>;
            /**
             * CapacityReservationSelectorTerms is a list of capacity reservation selector terms. Each term is ORed together to
             * determine the set of eligible capacity reservations.
             */
            capacityReservationSelectorTerms?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecCapacityReservationSelectorTermsArgs>[]>;
            /**
             * Context is a Reserved field in EC2 APIs
             * https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateFleet.html
             */
            context?: pulumi.Input<string>;
            /**
             * DetailedMonitoring controls if detailed monitoring is enabled for instances that are launched
             */
            detailedMonitoring?: pulumi.Input<boolean>;
            /**
             * InstanceProfile is the AWS entity that instances use.
             * This field is mutually exclusive from role.
             * The instance profile should already have a role assigned to it that Karpenter
             *  has PassRole permission on for instance launch using this instanceProfile to succeed.
             */
            instanceProfile?: pulumi.Input<string>;
            /**
             * InstanceStorePolicy specifies how to handle instance-store disks.
             */
            instanceStorePolicy?: pulumi.Input<string>;
            /**
             * IPPrefixCount sets the number of IPv4 prefixes to be automatically assigned to the network interface.
             */
            ipPrefixCount?: pulumi.Input<number>;
            /**
             * Kubelet defines args to be used when configuring kubelet on provisioned nodes.
             * They are a subset of the upstream types, recognizing not all options may be supported.
             * Wherever possible, the types and names should reflect the upstream kubelet types.
             */
            kubelet?: pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecKubeletArgs>;
            /**
             * MetadataOptions for the generated launch template of provisioned nodes.
             *
             * This specifies the exposure of the Instance Metadata Service to
             * provisioned EC2 nodes. For more information,
             * see Instance Metadata and User Data
             * (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html)
             * in the Amazon Elastic Compute Cloud User Guide.
             *
             * Refer to recommended, security best practices
             * (https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node)
             * for limiting exposure of Instance Metadata and User Data to pods.
             * If omitted, defaults to httpEndpoint enabled, with httpProtocolIPv6
             * disabled, with httpPutResponseLimit of 1, and with httpTokens
             * required.
             */
            metadataOptions?: pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecMetadataOptionsArgs>;
            /**
             * NetworkInterfaces specifies the network interface configurations to be attached to provisioned instances.
             */
            networkInterfaces?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecNetworkInterfacesArgs>[]>;
            /**
             * PlacementGroupSelector defines the name or the id of the placement to resolve with the nodeclass.
             */
            placementGroupSelector?: pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecPlacementGroupSelectorArgs>;
            /**
             * Role is the AWS identity that nodes use.
             * This field is mutually exclusive from instanceProfile.
             */
            role?: pulumi.Input<string>;
            /**
             * SecurityGroupSelectorTerms is a list of security group selector terms. The terms are ORed.
             */
            securityGroupSelectorTerms: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecSecurityGroupSelectorTermsArgs>[]>;
            /**
             * SubnetSelectorTerms is a list of subnet selector terms. The terms are ORed.
             */
            subnetSelectorTerms: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecSubnetSelectorTermsArgs>[]>;
            /**
             * Tags to be applied on ec2 resources like instances and launch templates.
             */
            tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * UserData to be applied to the provisioned nodes.
             * It must be in the appropriate format based on the AMIFamily in use. Karpenter will merge certain fields into
             * this UserData to ensure nodes are being provisioned with the correct configuration.
             */
            userData?: pulumi.Input<string>;
        }
        /**
         * ec2nodeClassSpecArgsProvideDefaults sets the appropriate defaults for EC2NodeClassSpecArgs
         */
        export function ec2nodeClassSpecArgsProvideDefaults(val: EC2NodeClassSpecArgs): EC2NodeClassSpecArgs {
            return {
                ...val,
                metadataOptions: (val.metadataOptions ? pulumi.output(val.metadataOptions).apply(inputs.karpenter.v1.ec2nodeClassSpecMetadataOptionsArgsProvideDefaults) : undefined),
            };
        }

        /**
         * AMISelectorTerm defines selection logic for an ami used by Karpenter to launch nodes.
         * If multiple fields are used for selection, the requirements are ANDed.
         */
        export interface EC2NodeClassSpecAmiSelectorTermsArgs {
            /**
             * Alias specifies which EKS optimized AMI to select.
             * Each alias consists of a family and an AMI version, specified as "family@version".
             * Valid families include: al2, al2023, bottlerocket, windows2019, windows2022, windows2025.
             * The version can either be pinned to a specific AMI release, with that AMIs version format (ex: "al2023@v20240625" or "bottlerocket@v1.10.0").
             * The version can also be set to "latest" for any family. Setting the version to latest will result in drift when a new AMI is released. This is **not** recommended for production environments.
             * Note: The Windows families do **not** support version pinning, and only latest may be used.
             */
            alias?: pulumi.Input<string>;
            /**
             * ID is the ami id in EC2
             */
            id?: pulumi.Input<string>;
            /**
             * Name is the ami name in EC2.
             * This value is the name field, which is different from the name tag.
             */
            name?: pulumi.Input<string>;
            /**
             * Owner is the owner for the ami.
             * You can specify a combination of AWS account IDs, "self", "amazon", and "aws-marketplace"
             */
            owner?: pulumi.Input<string>;
            /**
             * SSMParameter is the name (or ARN) of the SSM parameter containing the Image ID.
             */
            ssmParameter?: pulumi.Input<string>;
            /**
             * Tags is a map of key/value tags used to select amis.
             * Specifying '*' for a value selects all values for a given tag key.
             */
            tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        }

        export interface EC2NodeClassSpecBlockDeviceMappingsArgs {
            /**
             * The device name (for example, /dev/sdh or xvdh).
             */
            deviceName?: pulumi.Input<string>;
            /**
             * EBS contains parameters used to automatically set up EBS volumes when an instance is launched.
             */
            ebs?: pulumi.Input<inputs.karpenter.v1.EC2NodeClassSpecBlockDeviceMappingsEbsArgs>;
            /**
             * RootVolume is a flag indicating if this device is mounted as kubelet root dir. You can
             * configure at most one root volume in BlockDeviceMappings.
             */
            rootVolume?: pulumi.Input<boolean>;
        }

        /**
         * EBS contains parameters used to automatically set up EBS volumes when an instance is launched.
         */
        export interface EC2NodeClassSpecBlockDeviceMappingsEbsArgs {
            /**
             * DeleteOnTermination indicates whether the EBS volume is deleted on instance termination.
             */
            deleteOnTermination?: pulumi.Input<boolean>;
            /**
             * Encrypted indicates whether the EBS volume is encrypted. Encrypted volumes can only
             * be attached to instances that support Amazon EBS encryption. If you are creating
             * a volume from a snapshot, you can't specify an encryption value.
             */
            encrypted?: pulumi.Input<boolean>;
            /**
             * IOPS is the number of I/O operations per second (IOPS). For gp3, io1, and io2 volumes,
             * this represents the number of IOPS that are provisioned for the volume. For
             * gp2 volumes, this represents the baseline performance of the volume and the
             * rate at which the volume accumulates I/O credits for bursting.
             *
             * The following are the supported values for each volume type:
             *
             *    * gp3: 3,000-16,000 IOPS
             *
             *    * io1: 100-64,000 IOPS
             *
             *    * io2: 100-64,000 IOPS
             *
             * For io1 and io2 volumes, we guarantee 64,000 IOPS only for Instances built
             * on the Nitro System (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances).
             * Other instance families guarantee performance up to 32,000 IOPS.
             *
             * This parameter is supported for io1, io2, and gp3 volumes only. This parameter
             * is not supported for gp2, st1, sc1, or standard volumes.
             */
            iops?: pulumi.Input<number>;
            /**
             * Identifier (key ID, key alias, key ARN, or alias ARN) of the customer managed KMS key to use for EBS encryption.
             */
            kmsKeyID?: pulumi.Input<string>;
            /**
             * SnapshotID is the ID of an EBS snapshot
             */
            snapshotID?: pulumi.Input<string>;
            /**
             * Throughput to provision for a gp3 volume, with a maximum of 1,000 MiB/s.
             * Valid Range: Minimum value of 125. Maximum value of 1000.
             */
            throughput?: pulumi.Input<number>;
            /**
             * VolumeInitializationRate specifies the Amazon EBS Provisioned Rate for Volume Initialization,
             * in MiB/s, at which to download the snapshot blocks from Amazon S3 to the volume. This is also known as volume
             * initialization. Specifying a volume initialization rate ensures that the volume is initialized at a
             * predictable and consistent rate after creation. Only allowed if SnapshotID is set.
             * Valid Range: Minimum value of 100. Maximum value of 300.
             */
            volumeInitializationRate?: pulumi.Input<number>;
            /**
             * VolumeSize in `Gi`, `G`, `Ti`, or `T`. You must specify either a snapshot ID or
             * a volume size. The following are the supported volumes sizes for each volume
             * type:
             *
             *    * gp2 and gp3: 1-16,384
             *
             *    * io1 and io2: 4-16,384
             *
             *    * st1 and sc1: 125-16,384
             *
             *    * standard: 1-1,024
             */
            volumeSize?: pulumi.Input<string>;
            /**
             * VolumeType of the block device.
             * For more information, see Amazon EBS volume types (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html)
             * in the Amazon Elastic Compute Cloud User Guide.
             */
            volumeType?: pulumi.Input<string>;
        }

        export interface EC2NodeClassSpecCapacityReservationSelectorTermsArgs {
            /**
             * ID is the capacity reservation id in EC2
             */
            id?: pulumi.Input<string>;
            /**
             * InstanceMatchCriteria specifies how instances are matched to capacity reservations.
             */
            instanceMatchCriteria?: pulumi.Input<string>;
            /**
             * Owner is the owner id for the ami.
             */
            ownerID?: pulumi.Input<string>;
            /**
             * Tags is a map of key/value tags used to select capacity reservations.
             * Specifying '*' for a value selects all values for a given tag key.
             */
            tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        }

        /**
         * Kubelet defines args to be used when configuring kubelet on provisioned nodes.
         * They are a subset of the upstream types, recognizing not all options may be supported.
         * Wherever possible, the types and names should reflect the upstream kubelet types.
         */
        export interface EC2NodeClassSpecKubeletArgs {
            /**
             * clusterDNS is a list of IP addresses for the cluster DNS server.
             * Note that not all providers may use all addresses.
             */
            clusterDNS?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * CPUCFSQuota enables CPU CFS quota enforcement for containers that specify CPU limits.
             */
            cpuCFSQuota?: pulumi.Input<boolean>;
            /**
             * EvictionHard is the map of signal names to quantities that define hard eviction thresholds
             */
            evictionHard?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * EvictionMaxPodGracePeriod is the maximum allowed grace period (in seconds) to use when terminating pods in
             * response to soft eviction thresholds being met.
             */
            evictionMaxPodGracePeriod?: pulumi.Input<number>;
            /**
             * EvictionSoft is the map of signal names to quantities that define soft eviction thresholds
             */
            evictionSoft?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * EvictionSoftGracePeriod is the map of signal names to quantities that define grace periods for each eviction signal
             */
            evictionSoftGracePeriod?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * ImageGCHighThresholdPercent is the percent of disk usage after which image
             * garbage collection is always run. The percent is calculated by dividing this
             * field value by 100, so this field must be between 0 and 100, inclusive.
             * When specified, the value must be greater than ImageGCLowThresholdPercent.
             */
            imageGCHighThresholdPercent?: pulumi.Input<number>;
            /**
             * ImageGCLowThresholdPercent is the percent of disk usage before which image
             * garbage collection is never run. Lowest disk usage to garbage collect to.
             * The percent is calculated by dividing this field value by 100,
             * so the field value must be between 0 and 100, inclusive.
             * When specified, the value must be less than imageGCHighThresholdPercent
             */
            imageGCLowThresholdPercent?: pulumi.Input<number>;
            /**
             * KubeReserved contains resources reserved for Kubernetes system components.
             */
            kubeReserved?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * MaxPods is an override for the maximum number of pods that can run on
             * a worker node instance.
             */
            maxPods?: pulumi.Input<number>;
            /**
             * PodsPerCore is an override for the number of pods that can run on a worker node
             * instance based on the number of cpu cores. This value cannot exceed MaxPods, so, if
             * MaxPods is a lower value, that value will be used.
             */
            podsPerCore?: pulumi.Input<number>;
            /**
             * SystemReserved contains resources reserved for OS system daemons and kernel memory.
             */
            systemReserved?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        }

        /**
         * MetadataOptions for the generated launch template of provisioned nodes.
         *
         * This specifies the exposure of the Instance Metadata Service to
         * provisioned EC2 nodes. For more information,
         * see Instance Metadata and User Data
         * (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html)
         * in the Amazon Elastic Compute Cloud User Guide.
         *
         * Refer to recommended, security best practices
         * (https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node)
         * for limiting exposure of Instance Metadata and User Data to pods.
         * If omitted, defaults to httpEndpoint enabled, with httpProtocolIPv6
         * disabled, with httpPutResponseLimit of 1, and with httpTokens
         * required.
         */
        export interface EC2NodeClassSpecMetadataOptionsArgs {
            /**
             * HTTPEndpoint enables or disables the HTTP metadata endpoint on provisioned
             * nodes. If metadata options is non-nil, but this parameter is not specified,
             * the default state is "enabled".
             *
             * If you specify a value of "disabled", instance metadata will not be accessible
             * on the node.
             */
            httpEndpoint?: pulumi.Input<string>;
            /**
             * HTTPProtocolIPv6 enables or disables the IPv6 endpoint for the instance metadata
             * service on provisioned nodes. If metadata options is non-nil, but this parameter
             * is not specified, the default state is "disabled".
             */
            httpProtocolIPv6?: pulumi.Input<string>;
            /**
             * HTTPPutResponseHopLimit is the desired HTTP PUT response hop limit for
             * instance metadata requests. The larger the number, the further instance
             * metadata requests can travel. Possible values are integers from 1 to 64.
             * If metadata options is non-nil, but this parameter is not specified, the
             * default value is 1.
             */
            httpPutResponseHopLimit?: pulumi.Input<number>;
            /**
             * HTTPTokens determines the state of token usage for instance metadata
             * requests. If metadata options is non-nil, but this parameter is not
             * specified, the default state is "required".
             *
             * If the state is optional, one can choose to retrieve instance metadata with
             * or without a signed token header on the request. If one retrieves the IAM
             * role credentials without a token, the version 1.0 role credentials are
             * returned. If one retrieves the IAM role credentials using a valid signed
             * token, the version 2.0 role credentials are returned.
             *
             * If the state is "required", one must send a signed token header with any
             * instance metadata retrieval requests. In this state, retrieving the IAM
             * role credentials always returns the version 2.0 credentials; the version
             * 1.0 credentials are not available.
             */
            httpTokens?: pulumi.Input<string>;
        }
        /**
         * ec2nodeClassSpecMetadataOptionsArgsProvideDefaults sets the appropriate defaults for EC2NodeClassSpecMetadataOptionsArgs
         */
        export function ec2nodeClassSpecMetadataOptionsArgsProvideDefaults(val: EC2NodeClassSpecMetadataOptionsArgs): EC2NodeClassSpecMetadataOptionsArgs {
            return {
                ...val,
                httpEndpoint: (val.httpEndpoint) ?? "enabled",
                httpProtocolIPv6: (val.httpProtocolIPv6) ?? "disabled",
                httpPutResponseHopLimit: (val.httpPutResponseHopLimit) ?? 1,
                httpTokens: (val.httpTokens) ?? "required",
            };
        }

        /**
         * NetworkInterface specifies the configuration for a network interface to be attached
         * to provisioned instances.
         */
        export interface EC2NodeClassSpecNetworkInterfacesArgs {
            /**
             * DeviceIndex is the device index for the network interface attachment.
             */
            deviceIndex: pulumi.Input<number>;
            /**
             * InterfaceType is the type of network interface. Valid values are "interface" and "efa-only".
             */
            interfaceType: pulumi.Input<string>;
            /**
             * NetworkCardIndex is the index of the network card to attach the interface to.
             */
            networkCardIndex: pulumi.Input<number>;
        }

        /**
         * PlacementGroupSelector defines the name or the id of the placement to resolve with the nodeclass.
         */
        export interface EC2NodeClassSpecPlacementGroupSelectorArgs {
            /**
             * ID is the placement group id in EC2
             */
            id?: pulumi.Input<string>;
            /**
             * Name is the placement group name in EC2
             */
            name?: pulumi.Input<string>;
        }

        /**
         * SecurityGroupSelectorTerm defines selection logic for a security group used by Karpenter to launch nodes.
         * If multiple fields are used for selection, the requirements are ANDed.
         */
        export interface EC2NodeClassSpecSecurityGroupSelectorTermsArgs {
            /**
             * ID is the security group id in EC2
             */
            id?: pulumi.Input<string>;
            /**
             * Name is the security group name in EC2.
             * This value is the name field, which is different from the name tag.
             */
            name?: pulumi.Input<string>;
            /**
             * Tags is a map of key/value tags used to select security groups.
             * Specifying '*' for a value selects all values for a given tag key.
             */
            tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        }

        /**
         * SubnetSelectorTerm defines selection logic for a subnet used by Karpenter to launch nodes.
         * If multiple fields are used for selection, the requirements are ANDed.
         */
        export interface EC2NodeClassSpecSubnetSelectorTermsArgs {
            /**
             * ID is the subnet id in EC2
             */
            id?: pulumi.Input<string>;
            /**
             * Tags is a map of key/value tags used to select subnets
             * Specifying '*' for a value selects all values for a given tag key.
             */
            tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        }

        /**
         * EC2NodeClassStatus contains the resolved state of the EC2NodeClass
         */
        export interface EC2NodeClassStatusArgs {
            /**
             * AMI contains the current AMI values that are available to the
             * cluster under the AMI selectors.
             */
            amis?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassStatusAmisArgs>[]>;
            /**
             * CapacityReservations contains the current capacity reservation values that are available to this NodeClass under the
             * CapacityReservation selectors.
             */
            capacityReservations?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassStatusCapacityReservationsArgs>[]>;
            /**
             * Conditions contains signals for health and readiness
             */
            conditions?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassStatusConditionsArgs>[]>;
            /**
             * InstanceProfile contains the resolved instance profile for the role
             */
            instanceProfile?: pulumi.Input<string>;
            /**
             * SecurityGroups contains the current security group values that are available to the
             * cluster under the SecurityGroups selectors.
             */
            securityGroups?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassStatusSecurityGroupsArgs>[]>;
            /**
             * Subnets contains the current subnet values that are available to the
             * cluster under the subnet selectors.
             */
            subnets?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassStatusSubnetsArgs>[]>;
        }

        /**
         * AMI contains resolved AMI selector values utilized for node launch
         */
        export interface EC2NodeClassStatusAmisArgs {
            /**
             * Deprecation status of the AMI
             */
            deprecated?: pulumi.Input<boolean>;
            /**
             * ID of the AMI
             */
            id: pulumi.Input<string>;
            /**
             * Name of the AMI
             */
            name?: pulumi.Input<string>;
            /**
             * Requirements of the AMI to be utilized on an instance type
             */
            requirements: pulumi.Input<pulumi.Input<inputs.karpenter.v1.EC2NodeClassStatusAmisRequirementsArgs>[]>;
        }

        /**
         * A node selector requirement is a selector that contains values, a key, and an operator
         * that relates the key and values.
         */
        export interface EC2NodeClassStatusAmisRequirementsArgs {
            /**
             * The label key that the selector applies to.
             */
            key: pulumi.Input<string>;
            /**
             * Represents a key's relationship to a set of values.
             * Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
             */
            operator: pulumi.Input<string>;
            /**
             * An array of string values. If the operator is In or NotIn,
             * the values array must be non-empty. If the operator is Exists or DoesNotExist,
             * the values array must be empty. If the operator is Gt or Lt, the values
             * array must have a single element, which will be interpreted as an integer.
             * This array is replaced during a strategic merge patch.
             */
            values?: pulumi.Input<pulumi.Input<string>[]>;
        }

        export interface EC2NodeClassStatusCapacityReservationsArgs {
            /**
             * The availability zone the capacity reservation is available in.
             */
            availabilityZone: pulumi.Input<string>;
            /**
             * The time at which the capacity reservation expires. Once expired, the reserved capacity is released and Karpenter
             * will no longer be able to launch instances into that reservation.
             */
            endTime?: pulumi.Input<string>;
            /**
             * The id for the capacity reservation.
             */
            id: pulumi.Input<string>;
            /**
             * Indicates the type of instance launches the capacity reservation accepts.
             */
            instanceMatchCriteria: pulumi.Input<string>;
            /**
             * The instance type for the capacity reservation.
             */
            instanceType: pulumi.Input<string>;
            /**
             * Indicates whether this capacity reservation is interruptible
             */
            interruptible?: pulumi.Input<boolean>;
            /**
             * The ID of the AWS account that owns the capacity reservation.
             */
            ownerID: pulumi.Input<string>;
            /**
             * The type of capacity reservation.
             */
            reservationType?: pulumi.Input<string>;
            /**
             * The state of the capacity reservation. A capacity reservation is considered to be expiring if it is within the EC2
             * reclaimation window. Only capacity-block reservations may be in this state.
             */
            state?: pulumi.Input<string>;
        }
        /**
         * ec2nodeClassStatusCapacityReservationsArgsProvideDefaults sets the appropriate defaults for EC2NodeClassStatusCapacityReservationsArgs
         */
        export function ec2nodeClassStatusCapacityReservationsArgsProvideDefaults(val: EC2NodeClassStatusCapacityReservationsArgs): EC2NodeClassStatusCapacityReservationsArgs {
            return {
                ...val,
                reservationType: (val.reservationType) ?? "default",
                state: (val.state) ?? "active",
            };
        }

        /**
         * Condition aliases the upstream type and adds additional helper methods
         */
        export interface EC2NodeClassStatusConditionsArgs {
            /**
             * lastTransitionTime is the last time the condition transitioned from one status to another.
             * This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
             */
            lastTransitionTime: pulumi.Input<string>;
            /**
             * message is a human readable message indicating details about the transition.
             * This may be an empty string.
             */
            message: pulumi.Input<string>;
            /**
             * observedGeneration represents the .metadata.generation that the condition was set based upon.
             * For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
             * with respect to the current state of the instance.
             */
            observedGeneration?: pulumi.Input<number>;
            /**
             * reason contains a programmatic identifier indicating the reason for the condition's last transition.
             * Producers of specific condition types may define expected values and meanings for this field,
             * and whether the values are considered a guaranteed API.
             * The value should be a CamelCase string.
             * This field may not be empty.
             */
            reason: pulumi.Input<string>;
            /**
             * status of the condition, one of True, False, Unknown.
             */
            status: pulumi.Input<string>;
            /**
             * type of condition in CamelCase or in foo.example.com/CamelCase.
             */
            type: pulumi.Input<string>;
        }

        /**
         * SecurityGroup contains resolved SecurityGroup selector values utilized for node launch
         */
        export interface EC2NodeClassStatusSecurityGroupsArgs {
            /**
             * ID of the security group
             */
            id: pulumi.Input<string>;
            /**
             * Name of the security group
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Subnet contains resolved Subnet selector values utilized for node launch
         */
        export interface EC2NodeClassStatusSubnetsArgs {
            /**
             * ID of the subnet
             */
            id: pulumi.Input<string>;
            /**
             * The associated availability zone
             */
            zone: pulumi.Input<string>;
            /**
             * The associated availability zone ID
             */
            zoneID?: pulumi.Input<string>;
        }

        /**
         * NodeClaimSpec describes the desired state of the NodeClaim
         */
        export interface NodeClaimSpecArgs {
            /**
             * ExpireAfter is the duration the controller will wait
             * before terminating a node, measured from when the node is created. This
             * is useful to implement features like eventually consistent node upgrade,
             * memory leak protection, and disruption testing.
             */
            expireAfter?: pulumi.Input<string>;
            /**
             * NodeClassRef is a reference to an object that defines provider specific configuration
             */
            nodeClassRef: pulumi.Input<inputs.karpenter.v1.NodeClaimSpecNodeClassRefArgs>;
            /**
             * Requirements are layered with GetLabels and applied to every node.
             */
            requirements: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodeClaimSpecRequirementsArgs>[]>;
            /**
             * Resources models the resource requirements for the NodeClaim to launch
             */
            resources?: pulumi.Input<inputs.karpenter.v1.NodeClaimSpecResourcesArgs>;
            /**
             * StartupTaints are taints that are applied to nodes upon startup which are expected to be removed automatically
             * within a short period of time, typically by a DaemonSet that tolerates the taint. These are commonly used by
             * daemonsets to allow initialization and enforce startup ordering.  StartupTaints are ignored for provisioning
             * purposes in that pods are not required to tolerate a StartupTaint in order to have nodes provisioned for them.
             */
            startupTaints?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodeClaimSpecStartupTaintsArgs>[]>;
            /**
             * Taints will be applied to the NodeClaim's node.
             */
            taints?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodeClaimSpecTaintsArgs>[]>;
            /**
             * TerminationGracePeriod is the maximum duration the controller will wait before forcefully deleting the pods on a node, measured from when deletion is first initiated.
             *
             * Warning: this feature takes precedence over a Pod's terminationGracePeriodSeconds value, and bypasses any blocked PDBs or the karpenter.sh/do-not-disrupt annotation.
             *
             * This field is intended to be used by cluster administrators to enforce that nodes can be cycled within a given time period.
             * When set, drifted nodes will begin draining even if there are pods blocking eviction. Draining will respect PDBs and the do-not-disrupt annotation until the TGP is reached.
             *
             * Karpenter will preemptively delete pods so their terminationGracePeriodSeconds align with the node's terminationGracePeriod.
             * If a pod would be terminated without being granted its full terminationGracePeriodSeconds prior to the node timeout,
             * that pod will be deleted at T = node timeout - pod terminationGracePeriodSeconds.
             *
             * The feature can also be used to allow maximum time limits for long-running jobs which can delay node termination with preStop hooks.
             * If left undefined, the controller will wait indefinitely for pods to be drained.
             */
            terminationGracePeriod?: pulumi.Input<string>;
        }
        /**
         * nodeClaimSpecArgsProvideDefaults sets the appropriate defaults for NodeClaimSpecArgs
         */
        export function nodeClaimSpecArgsProvideDefaults(val: NodeClaimSpecArgs): NodeClaimSpecArgs {
            return {
                ...val,
                expireAfter: (val.expireAfter) ?? "720h",
            };
        }

        /**
         * NodeClassRef is a reference to an object that defines provider specific configuration
         */
        export interface NodeClaimSpecNodeClassRefArgs {
            /**
             * API version of the referent
             */
            group: pulumi.Input<string>;
            /**
             * Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
             */
            kind: pulumi.Input<string>;
            /**
             * Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names
             */
            name: pulumi.Input<string>;
        }

        /**
         * A node selector requirement is a selector that contains values, a key, an operator that relates the key and values
         * and minValues that represent the requirement to have at least that many values.
         */
        export interface NodeClaimSpecRequirementsArgs {
            /**
             * The label key that the selector applies to.
             */
            key: pulumi.Input<string>;
            /**
             * This field is ALPHA and can be dropped or replaced at any time
             * MinValues is the minimum number of unique values required to define the flexibility of the specific requirement.
             */
            minValues?: pulumi.Input<number>;
            /**
             * Represents a key's relationship to a set of values.
             * Valid operators are In, NotIn, Exists, DoesNotExist. Gt, Lt, Gte, and Lte.
             */
            operator: pulumi.Input<string>;
            /**
             * An array of string values. If the operator is In or NotIn,
             * the values array must be non-empty. If the operator is Exists or DoesNotExist,
             * the values array must be empty. If the operator is Gt, Lt, Gte, or Lte, the values
             * array must have a single element, which will be interpreted as an integer.
             * This array is replaced during a strategic merge patch.
             */
            values?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * Resources models the resource requirements for the NodeClaim to launch
         */
        export interface NodeClaimSpecResourcesArgs {
            /**
             * Requests describes the minimum required resources for the NodeClaim to launch
             */
            requests?: pulumi.Input<{[key: string]: pulumi.Input<number | string>}>;
        }

        /**
         * The node this Taint is attached to has the "effect" on
         * any pod that does not tolerate the Taint.
         */
        export interface NodeClaimSpecStartupTaintsArgs {
            /**
             * Required. The effect of the taint on pods
             * that do not tolerate the taint.
             * Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
             */
            effect: pulumi.Input<string>;
            /**
             * Required. The taint key to be applied to a node.
             */
            key: pulumi.Input<string>;
            /**
             * TimeAdded represents the time at which the taint was added.
             */
            timeAdded?: pulumi.Input<string>;
            /**
             * The taint value corresponding to the taint key.
             */
            value?: pulumi.Input<string>;
        }

        /**
         * The node this Taint is attached to has the "effect" on
         * any pod that does not tolerate the Taint.
         */
        export interface NodeClaimSpecTaintsArgs {
            /**
             * Required. The effect of the taint on pods
             * that do not tolerate the taint.
             * Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
             */
            effect: pulumi.Input<string>;
            /**
             * Required. The taint key to be applied to a node.
             */
            key: pulumi.Input<string>;
            /**
             * TimeAdded represents the time at which the taint was added.
             */
            timeAdded?: pulumi.Input<string>;
            /**
             * The taint value corresponding to the taint key.
             */
            value?: pulumi.Input<string>;
        }

        /**
         * NodeClaimStatus defines the observed state of NodeClaim
         */
        export interface NodeClaimStatusArgs {
            /**
             * Allocatable is the estimated allocatable capacity of the node
             */
            allocatable?: pulumi.Input<{[key: string]: pulumi.Input<number | string>}>;
            /**
             * Capacity is the estimated full capacity of the node
             */
            capacity?: pulumi.Input<{[key: string]: pulumi.Input<number | string>}>;
            /**
             * Conditions contains signals for health and readiness
             */
            conditions?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodeClaimStatusConditionsArgs>[]>;
            /**
             * ImageID is an identifier for the image that runs on the node
             */
            imageID?: pulumi.Input<string>;
            /**
             * LastPodEventTime is updated with the last time a pod was scheduled
             * or removed from the node. A pod going terminal or terminating
             * is also considered as removed.
             */
            lastPodEventTime?: pulumi.Input<string>;
            /**
             * NodeName is the name of the corresponding node object
             */
            nodeName?: pulumi.Input<string>;
            /**
             * ProviderID of the corresponding node object
             */
            providerID?: pulumi.Input<string>;
        }

        /**
         * Condition aliases the upstream type and adds additional helper methods
         */
        export interface NodeClaimStatusConditionsArgs {
            /**
             * lastTransitionTime is the last time the condition transitioned from one status to another.
             * This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
             */
            lastTransitionTime: pulumi.Input<string>;
            /**
             * message is a human readable message indicating details about the transition.
             * This may be an empty string.
             */
            message?: pulumi.Input<string>;
            /**
             * observedGeneration represents the .metadata.generation that the condition was set based upon.
             * For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
             * with respect to the current state of the instance.
             */
            observedGeneration?: pulumi.Input<number>;
            /**
             * reason contains a programmatic identifier indicating the reason for the condition's last transition.
             * Producers of specific condition types may define expected values and meanings for this field,
             * and whether the values are considered a guaranteed API.
             * The value should be a CamelCase string.
             * This field may not be empty.
             */
            reason?: pulumi.Input<string>;
            /**
             * status of the condition, one of True, False, Unknown.
             */
            status: pulumi.Input<string>;
            /**
             * type of condition in CamelCase or in foo.example.com/CamelCase.
             */
            type: pulumi.Input<string>;
        }

        /**
         * NodePoolSpec is the top level nodepool specification. Nodepools
         * launch nodes in response to pods that are unschedulable. A single nodepool
         * is capable of managing a diverse set of nodes. Node properties are determined
         * from a combination of nodepool and pod scheduling constraints.
         */
        export interface NodePoolSpecArgs {
            /**
             * Disruption contains the parameters that relate to Karpenter's disruption logic
             */
            disruption?: pulumi.Input<inputs.karpenter.v1.NodePoolSpecDisruptionArgs>;
            /**
             * Limits define a set of bounds for provisioning capacity.
             * Limits other than limits.nodes is not supported when replicas is set.
             */
            limits?: pulumi.Input<{[key: string]: pulumi.Input<number | string>}>;
            /**
             * Replicas is the desired number of nodes for the NodePool. When specified, the NodePool will
             * maintain this fixed number of replicas rather than scaling based on pod demand.
             * When replicas is set:
             *   - The following fields are ignored:
             *       * disruption.consolidationPolicy
             *       * disruption.consolidateAfter
             *   - Only limits.nodes is supported; other resource limits (e.g., CPU, memory) must not be specified.
             *   - Weight is not supported.
             * Note: This field is alpha.
             */
            replicas?: pulumi.Input<number>;
            /**
             * Template contains the template of possibilities for the provisioning logic to launch a NodeClaim with.
             * NodeClaims launched from this NodePool will often be further constrained than the template specifies.
             */
            template: pulumi.Input<inputs.karpenter.v1.NodePoolSpecTemplateArgs>;
            /**
             * Weight is the priority given to the nodepool during scheduling. A higher
             * numerical weight indicates that this nodepool will be ordered
             * ahead of other nodepools with lower weights. A nodepool with no weight
             * will be treated as if it is a nodepool with a weight of 0.
             * Weight is not supported when replicas is set.
             */
            weight?: pulumi.Input<number>;
        }
        /**
         * nodePoolSpecArgsProvideDefaults sets the appropriate defaults for NodePoolSpecArgs
         */
        export function nodePoolSpecArgsProvideDefaults(val: NodePoolSpecArgs): NodePoolSpecArgs {
            return {
                ...val,
                disruption: (val.disruption ? pulumi.output(val.disruption).apply(inputs.karpenter.v1.nodePoolSpecDisruptionArgsProvideDefaults) : undefined),
                template: pulumi.output(val.template).apply(inputs.karpenter.v1.nodePoolSpecTemplateArgsProvideDefaults),
            };
        }

        /**
         * Disruption contains the parameters that relate to Karpenter's disruption logic
         */
        export interface NodePoolSpecDisruptionArgs {
            /**
             * Budgets is a list of Budgets.
             * If there are multiple active budgets, Karpenter uses
             * the most restrictive value. If left undefined,
             * this will default to one budget with a value to 10%.
             */
            budgets?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodePoolSpecDisruptionBudgetsArgs>[]>;
            /**
             * ConsolidateAfter is the duration the controller will wait
             * before attempting to terminate nodes that are underutilized.
             * Refer to ConsolidationPolicy for how underutilization is considered.
             * When replicas is set, ConsolidateAfter is simply ignored
             */
            consolidateAfter: pulumi.Input<string>;
            /**
             * ConsolidationPolicy describes which nodes Karpenter can disrupt through its consolidation
             * algorithm. This policy defaults to "WhenEmptyOrUnderutilized" if not specified
             * When replicas is set, ConsolidationPolicy is simply ignored
             */
            consolidationPolicy?: pulumi.Input<string>;
        }
        /**
         * nodePoolSpecDisruptionArgsProvideDefaults sets the appropriate defaults for NodePoolSpecDisruptionArgs
         */
        export function nodePoolSpecDisruptionArgsProvideDefaults(val: NodePoolSpecDisruptionArgs): NodePoolSpecDisruptionArgs {
            return {
                ...val,
                consolidationPolicy: (val.consolidationPolicy) ?? "WhenEmptyOrUnderutilized",
            };
        }

        /**
         * Budget defines when Karpenter will restrict the
         * number of Node Claims that can be terminating simultaneously.
         */
        export interface NodePoolSpecDisruptionBudgetsArgs {
            /**
             * Duration determines how long a Budget is active since each Schedule hit.
             * Only minutes and hours are accepted, as cron does not work in seconds.
             * If omitted, the budget is always active.
             * This is required if Schedule is set.
             * This regex has an optional 0s at the end since the duration.String() always adds
             * a 0s at the end.
             */
            duration?: pulumi.Input<string>;
            /**
             * Nodes dictates the maximum number of NodeClaims owned by this NodePool
             * that can be terminating at once. This is calculated by counting nodes that
             * have a deletion timestamp set, or are actively being deleted by Karpenter.
             * This field is required when specifying a budget.
             * This cannot be of type intstr.IntOrString since kubebuilder doesn't support pattern
             * checking for int nodes for IntOrString nodes.
             * Ref: https://github.com/kubernetes-sigs/controller-tools/blob/55efe4be40394a288216dab63156b0a64fb82929/pkg/crd/markers/validation.go#L379-L388
             */
            nodes: pulumi.Input<string>;
            /**
             * Reasons is a list of disruption methods that this budget applies to. If Reasons is not set, this budget applies to all methods.
             * Otherwise, this will apply to each reason defined.
             * allowed reasons are Underutilized, Empty, and Drifted.
             */
            reasons?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * Schedule specifies when a budget begins being active, following
             * the upstream cronjob syntax. If omitted, the budget is always active.
             * Timezones are not supported.
             * This field is required if Duration is set.
             */
            schedule?: pulumi.Input<string>;
        }
        /**
         * nodePoolSpecDisruptionBudgetsArgsProvideDefaults sets the appropriate defaults for NodePoolSpecDisruptionBudgetsArgs
         */
        export function nodePoolSpecDisruptionBudgetsArgsProvideDefaults(val: NodePoolSpecDisruptionBudgetsArgs): NodePoolSpecDisruptionBudgetsArgs {
            return {
                ...val,
                nodes: (val.nodes) ?? "10%",
            };
        }

        /**
         * Template contains the template of possibilities for the provisioning logic to launch a NodeClaim with.
         * NodeClaims launched from this NodePool will often be further constrained than the template specifies.
         */
        export interface NodePoolSpecTemplateArgs {
            metadata?: pulumi.Input<inputs.karpenter.v1.NodePoolSpecTemplateMetadataArgs>;
            /**
             * NodeClaimTemplateSpec describes the desired state of the NodeClaim in the Nodepool
             * NodeClaimTemplateSpec is used in the NodePool's NodeClaimTemplate, with the resource requests omitted since
             * users are not able to set resource requests in the NodePool.
             */
            spec: pulumi.Input<inputs.karpenter.v1.NodePoolSpecTemplateSpecArgs>;
        }
        /**
         * nodePoolSpecTemplateArgsProvideDefaults sets the appropriate defaults for NodePoolSpecTemplateArgs
         */
        export function nodePoolSpecTemplateArgsProvideDefaults(val: NodePoolSpecTemplateArgs): NodePoolSpecTemplateArgs {
            return {
                ...val,
                spec: pulumi.output(val.spec).apply(inputs.karpenter.v1.nodePoolSpecTemplateSpecArgsProvideDefaults),
            };
        }

        export interface NodePoolSpecTemplateMetadataArgs {
            /**
             * Annotations is an unstructured key value map stored with a resource that may be
             * set by external tools to store and retrieve arbitrary metadata. They are not
             * queryable and should be preserved when modifying objects.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
             */
            annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * Map of string keys and values that can be used to organize and categorize
             * (scope and select) objects. May match selectors of replication controllers
             * and services.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
             */
            labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        }

        /**
         * NodeClaimTemplateSpec describes the desired state of the NodeClaim in the Nodepool
         * NodeClaimTemplateSpec is used in the NodePool's NodeClaimTemplate, with the resource requests omitted since
         * users are not able to set resource requests in the NodePool.
         */
        export interface NodePoolSpecTemplateSpecArgs {
            /**
             * ExpireAfter is the duration the controller will wait
             * before terminating a node, measured from when the node is created. This
             * is useful to implement features like eventually consistent node upgrade,
             * memory leak protection, and disruption testing.
             */
            expireAfter?: pulumi.Input<string>;
            /**
             * NodeClassRef is a reference to an object that defines provider specific configuration
             */
            nodeClassRef: pulumi.Input<inputs.karpenter.v1.NodePoolSpecTemplateSpecNodeClassRefArgs>;
            /**
             * Requirements are layered with GetLabels and applied to every node.
             */
            requirements: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodePoolSpecTemplateSpecRequirementsArgs>[]>;
            /**
             * StartupTaints are taints that are applied to nodes upon startup which are expected to be removed automatically
             * within a short period of time, typically by a DaemonSet that tolerates the taint. These are commonly used by
             * daemonsets to allow initialization and enforce startup ordering.  StartupTaints are ignored for provisioning
             * purposes in that pods are not required to tolerate a StartupTaint in order to have nodes provisioned for them.
             */
            startupTaints?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodePoolSpecTemplateSpecStartupTaintsArgs>[]>;
            /**
             * Taints will be applied to the NodeClaim's node.
             */
            taints?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodePoolSpecTemplateSpecTaintsArgs>[]>;
            /**
             * TerminationGracePeriod is the maximum duration the controller will wait before forcefully deleting the pods on a node, measured from when deletion is first initiated.
             *
             * Warning: this feature takes precedence over a Pod's terminationGracePeriodSeconds value, and bypasses any blocked PDBs or the karpenter.sh/do-not-disrupt annotation.
             *
             * This field is intended to be used by cluster administrators to enforce that nodes can be cycled within a given time period.
             * When set, drifted nodes will begin draining even if there are pods blocking eviction. Draining will respect PDBs and the do-not-disrupt annotation until the TGP is reached.
             *
             * Karpenter will preemptively delete pods so their terminationGracePeriodSeconds align with the node's terminationGracePeriod.
             * If a pod would be terminated without being granted its full terminationGracePeriodSeconds prior to the node timeout,
             * that pod will be deleted at T = node timeout - pod terminationGracePeriodSeconds.
             *
             * The feature can also be used to allow maximum time limits for long-running jobs which can delay node termination with preStop hooks.
             * If left undefined, the controller will wait indefinitely for pods to be drained.
             */
            terminationGracePeriod?: pulumi.Input<string>;
        }
        /**
         * nodePoolSpecTemplateSpecArgsProvideDefaults sets the appropriate defaults for NodePoolSpecTemplateSpecArgs
         */
        export function nodePoolSpecTemplateSpecArgsProvideDefaults(val: NodePoolSpecTemplateSpecArgs): NodePoolSpecTemplateSpecArgs {
            return {
                ...val,
                expireAfter: (val.expireAfter) ?? "720h",
            };
        }

        /**
         * NodeClassRef is a reference to an object that defines provider specific configuration
         */
        export interface NodePoolSpecTemplateSpecNodeClassRefArgs {
            /**
             * API version of the referent
             */
            group: pulumi.Input<string>;
            /**
             * Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
             */
            kind: pulumi.Input<string>;
            /**
             * Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names
             */
            name: pulumi.Input<string>;
        }

        /**
         * A node selector requirement is a selector that contains values, a key, an operator that relates the key and values
         * and minValues that represent the requirement to have at least that many values.
         */
        export interface NodePoolSpecTemplateSpecRequirementsArgs {
            /**
             * The label key that the selector applies to.
             */
            key: pulumi.Input<string>;
            /**
             * This field is ALPHA and can be dropped or replaced at any time
             * MinValues is the minimum number of unique values required to define the flexibility of the specific requirement.
             */
            minValues?: pulumi.Input<number>;
            /**
             * Represents a key's relationship to a set of values.
             * Valid operators are In, NotIn, Exists, DoesNotExist. Gt, Lt, Gte, and Lte.
             */
            operator: pulumi.Input<string>;
            /**
             * An array of string values. If the operator is In or NotIn,
             * the values array must be non-empty. If the operator is Exists or DoesNotExist,
             * the values array must be empty. If the operator is Gt, Lt, Gte, or Lte, the values
             * array must have a single element, which will be interpreted as an integer.
             * This array is replaced during a strategic merge patch.
             */
            values?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * The node this Taint is attached to has the "effect" on
         * any pod that does not tolerate the Taint.
         */
        export interface NodePoolSpecTemplateSpecStartupTaintsArgs {
            /**
             * Required. The effect of the taint on pods
             * that do not tolerate the taint.
             * Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
             */
            effect: pulumi.Input<string>;
            /**
             * Required. The taint key to be applied to a node.
             */
            key: pulumi.Input<string>;
            /**
             * TimeAdded represents the time at which the taint was added.
             */
            timeAdded?: pulumi.Input<string>;
            /**
             * The taint value corresponding to the taint key.
             */
            value?: pulumi.Input<string>;
        }

        /**
         * The node this Taint is attached to has the "effect" on
         * any pod that does not tolerate the Taint.
         */
        export interface NodePoolSpecTemplateSpecTaintsArgs {
            /**
             * Required. The effect of the taint on pods
             * that do not tolerate the taint.
             * Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
             */
            effect: pulumi.Input<string>;
            /**
             * Required. The taint key to be applied to a node.
             */
            key: pulumi.Input<string>;
            /**
             * TimeAdded represents the time at which the taint was added.
             */
            timeAdded?: pulumi.Input<string>;
            /**
             * The taint value corresponding to the taint key.
             */
            value?: pulumi.Input<string>;
        }

        /**
         * NodePoolStatus defines the observed state of NodePool
         */
        export interface NodePoolStatusArgs {
            /**
             * Conditions contains signals for health and readiness
             */
            conditions?: pulumi.Input<pulumi.Input<inputs.karpenter.v1.NodePoolStatusConditionsArgs>[]>;
            /**
             * NodeClassObservedGeneration represents the observed nodeClass generation for referenced nodeClass. If this does not match
             * the actual NodeClass Generation, NodeRegistrationHealthy status condition on the NodePool will be reset
             */
            nodeClassObservedGeneration?: pulumi.Input<number>;
            /**
             * Nodes is the count of nodes associated with this NodePool
             */
            nodes?: pulumi.Input<number>;
            /**
             * Resources is the list of resources that have been provisioned.
             */
            resources?: pulumi.Input<{[key: string]: pulumi.Input<number | string>}>;
        }
        /**
         * nodePoolStatusArgsProvideDefaults sets the appropriate defaults for NodePoolStatusArgs
         */
        export function nodePoolStatusArgsProvideDefaults(val: NodePoolStatusArgs): NodePoolStatusArgs {
            return {
                ...val,
                nodes: (val.nodes) ?? 0,
            };
        }

        /**
         * Condition aliases the upstream type and adds additional helper methods
         */
        export interface NodePoolStatusConditionsArgs {
            /**
             * lastTransitionTime is the last time the condition transitioned from one status to another.
             * This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
             */
            lastTransitionTime: pulumi.Input<string>;
            /**
             * message is a human readable message indicating details about the transition.
             * This may be an empty string.
             */
            message: pulumi.Input<string>;
            /**
             * observedGeneration represents the .metadata.generation that the condition was set based upon.
             * For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
             * with respect to the current state of the instance.
             */
            observedGeneration?: pulumi.Input<number>;
            /**
             * reason contains a programmatic identifier indicating the reason for the condition's last transition.
             * Producers of specific condition types may define expected values and meanings for this field,
             * and whether the values are considered a guaranteed API.
             * The value should be a CamelCase string.
             * This field may not be empty.
             */
            reason: pulumi.Input<string>;
            /**
             * status of the condition, one of True, False, Unknown.
             */
            status: pulumi.Input<string>;
            /**
             * type of condition in CamelCase or in foo.example.com/CamelCase.
             */
            type: pulumi.Input<string>;
        }

    }
}
